apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.portainer}}
  name: {{.Values.edgex.app.portainer}}
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.portainer}}
  type: ClusterIP
