apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.support.notifications}}
  name: {{.Values.edgex.app.support.notifications}}
spec:
  ports:
  - name: "48060"
    port: 48060
    targetPort: 48060
  {{- if eq .Values.edgex.serviceType "NodePort" }}
    nodePort: 48060
  {{- end}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.support.notifications}}
  type: {{.Values.edgex.serviceType}}
