apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.device.rest}}
  name: {{.Values.edgex.app.device.rest}}
spec:
  ports:
  - name: "49986"
    port: 49986
    targetPort: 49986
  {{- if eq .Values.edgex.serviceType "NodePort" }}
    nodePort: 49986
  {{- end}}
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.device.rest}}
  type: {{.Values.edgex.serviceType}}
